### ISSUE TITLE
Miner can't connect because of Unsupported method

### ISSUE THREAD

**Issue by agony123123** [Bytom/btmcpool#1]
Running the classic bytom node, and this btmcpool, I get the error pasted below, when trying to connect with a miner.

INFO[0000] init server state                             id=0 service=stratum_btm.0.prod
INFO[0000] start node syncing                            interval=100ms service=stratum_btm.0.prod
INFO[0000] service start running                         name=stratum_btm.0 service=stratum_btm.0.prod
INFO[0000] start listening                               port=9119 service=stratum_btm.0.prod
INFO[0000] broadcasting new jobs                         service=stratum_btm.0.prod sessions=0
INFO[0012] connection accepted                           service=stratum_btm.0.prod session_id=0 session_ip=10.0.0.109
INFO[0012] start job scheduler                           service=stratum_btm.0.prod session_id=0
INFO[0012] session dispatch                              service=stratum_btm.0.prod session_id=0 session_ip=10.0.0.109
ERRO[0012] unsupported method                            method=login service=stratum_btm.0.prod session_id=0 session_ip=10.0.0.109
ERRO[0012] client disconnected                           service=stratum_btm.0.prod session_id=0 session_ip=10.0.0.109
INFO[0012] session closed                                service=stratum_btm.0.prod session_id=0 session_ip=10.0.0.109

It seems like the "login" logic is not built, but cannot be circumvented.

**Comment by yyko** [comment]
@@agony123123
 
agony123123 Did you find a solution to this issue?

**Comment by MartinBTM** [comment]
please wait for our developer

**Comment by yasyzb** [comment]
fixed, pls use latest code.
